name: Run Unit Tests and Linting

on:
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your dependency installation command
        pip install pylint  # Install pylint for linting
        
    - name: Run unit tests
      run: python3 -m unittest discover -s tests
    
    - name: Run linting
      run: pylint *.py 
      
    - name: Check test and lint status
      run: |
        if [ $? -ne 0 ]; then
          echo "Tests or linting failed! Please fix them before merging."
          exit 1
        fi
        
    - name: Set status check
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.repos.createStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            context: 'unit-tests-and-linting'
          })
